In [33]:
# For python2,3 compatibility
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

In [34]:
%matplotlib inline
import numpy as np
import torch
import matplotlib.pyplot as plt

## Tensors 

Tensors are similar to NumPy's ndarrays, with the addition being that Tensors can also be used on a GPU to accelerate computing

Construct a randomly initiallized matrix

In [35]:
x=torch.rand(5,3)
print(x)

tensor([[0.1197, 0.9904, 0.1906],
        [0.3326, 0.1735, 0.7078],
        [0.7502, 0.0774, 0.0209],
        [0.7951, 0.5091, 0.5838],
        [0.4775, 0.3356, 0.0561]])


In [36]:
x.dtype

torch.float32

In [37]:
x=torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data

In [38]:
# Construct a tensor directly from data
x=torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user

new_tensor(data,dtype=None,device=None,requires_grad=False)->Tensor

Returns a new Tensor with data as the tensor data. 
By default, the returned Tensor has the same torch.dtype ans torch.device as this tensor

In [39]:
x = x.new_tensor([2,4])              # inherit its size (shape) and dtype      
print(x)
print(x.dtype)

x = torch.ones([5,3], dtype=torch.int)
print(x)
x = torch.randn_like(x, dtype = torch.float)     # override dtype
print(x)                                         # result has the same size                                                 

tensor([2., 4.])
torch.float32
tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)
tensor([[ 0.5042, -1.3807,  0.4933],
        [-0.9399,  1.7709, -1.1253],
        [ 0.8919, -0.2120,  0.1495],
        [ 2.4557,  1.5861, -1.2663],
        [ 1.8511, -0.5973,  2.1896]])


Get its size

<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.</p></div>

In [40]:
print(x.size())

torch.Size([5, 3])


## Operations
There are multiple syntaxes for operations. In the following example,
we will take a look at the addition operation.

Addition: syntax 1

In [41]:
y = torch.rand(5,3)
print(x + y)

tensor([[ 1.3609, -1.0984,  0.6881],
        [-0.7437,  2.6616, -0.9490],
        [ 1.5698,  0.0669,  0.2341],
        [ 2.6065,  2.1621, -1.0167],
        [ 2.0267, -0.0444,  2.9032]])


Addition: syntax 2

In [42]:
print(torch.add(x,y))

tensor([[ 1.3609, -1.0984,  0.6881],
        [-0.7437,  2.6616, -0.9490],
        [ 1.5698,  0.0669,  0.2341],
        [ 2.6065,  2.1621, -1.0167],
        [ 2.0267, -0.0444,  2.9032]])


Addition: in-place

In [43]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 1.3609, -1.0984,  0.6881],
        [-0.7437,  2.6616, -0.9490],
        [ 1.5698,  0.0669,  0.2341],
        [ 2.6065,  2.1621, -1.0167],
        [ 2.0267, -0.0444,  2.9032]])


<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!

In [44]:
print(x[:,1])

tensor([-1.3807,  1.7709, -0.2120,  1.5861, -0.5973])


Resizing: If you want to resize/reshape tensor, you can use torch.view

In [45]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8)   # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [46]:
x.t()   # transpose

tensor([[-0.7452, -0.5075,  1.3614,  2.1580],
        [-0.0002,  0.8289, -0.0235,  0.8317],
        [ 1.9823,  0.1144, -2.3446,  1.7880],
        [ 0.6352,  0.9542,  1.0783, -0.0307]])

If you have a one element tensor, use ``.item()`` to get the value as a Python number

In [47]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([1.4268])
1.4267522096633911


**Read later:**

100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc,,
are described
`here <http://pytorch.org/docs/torch>`.

# NumPy Bridge

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

<font color='red'>The Torch Tensor and NumPy array will share their underlying memory locations, and changing one will change the other.</font>

Converting a Torch Tensor to a NumPy Array   
    

In [48]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [49]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.

In [50]:
a.add_(1)      # 1 wil be broadcasting, so all element of a will increase by 1
print(a)
print(b)       # b=a.numpy() so a,b are share their underlying memory locations

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Converting NumPy Array to Torch Tensor

See how changing the np array changed the Torch Tensor automatically

In [51]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1,out=a)       # +1 to a
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to NumPy and back

Cuda Tensors
------------

Tensors can be moved onto any device using the ``.to`` method

let us run this cell only if CUDA is available
We will use ``torch.device`` objects to move tensors in and out of GPU


In [52]:
if torch.cuda.is_available():
    device = torch.device("cuda")         # a CUDA device object
    y = torch.ones_like(x, device=device) # directly create a tensor on GPU
    x = x.to(device)                      # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu",torch.double))       # ``.to`` can also change dtype together

tensor([2.4268], device='cuda:0')
tensor([2.4268], dtype=torch.float64)


cuda:0 printed because there's a chance to have multiple GPU

In [53]:
# more simply
if torch.cuda.is_available():
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.cuda()                           
    z = x + y
    print(z)
    print(z.cpu())

tensor([2.4268], device='cuda:0')
tensor([2.4268])
