In [18]:
# 1. 파이썬으로 딥러닝하기| CNN(Convolution Neural Network) Part1.이론 - https://everyday-deeplearning.tistory.com/entry/파이썬으로-딥러닝하기-CNNConvolution-Neural-Network 
# 2. 파이토치 docs - https://pytorch.org/docs/stable/nn.html

In [3]:
import numpy as np

In [7]:
input_ = np.array([[1,2,3,0],[0,1,2,3],[3,0,1,2],[2,3,0,1]])
filter_ = np.array([[2,0,1],[0,1,2],[1,0,2]])
bias = 3

In [28]:
def padding(input_,pad_width,mode='constant',constant_values=0):
    if mode == 'constant':
        result = np.zeros((input_.shape[0]+2*pad_width, input_.shape[1] + 2*pad_width))
        result[pad_width:pad_width+input_.shape[0],pad_width:pad_width+input_.shape[1]] = input_
        return result

In [35]:
padding(input_,1)

array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 2., 3., 0., 0.],
       [0., 0., 1., 2., 3., 0.],
       [0., 3., 0., 1., 2., 0.],
       [0., 2., 3., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [41]:
def conv2d(input_,filter_,bias,pad_width=0):
    input_ = np.pad(input_,pad_width=pad_width, mode='constant',constant_values=0)
    a = input_.shape[0] - filter_.shape[0] + 1
    b = input_.shape[1] - filter_.shape[1] + 1
    result2 = []

    for rn in range(a):
        for cn in range(b):
            result1 = input_[rn:rn+filter_.shape[0],cn:cn+filter_.shape[1]] * filter_
            result2.append(np.sum(result1) + bias)
    
    result = np.array(result2).reshape(a,b)
    return result

In [42]:
conv2d(input_,filter_,bias)

array([[18, 19],
       [ 9, 18]])

In [43]:
conv2d(input_,filter_,bias=0,pad_width=1)

array([[ 7, 12, 10,  2],
       [ 4, 15, 16, 10],
       [10,  6, 15,  6],
       [ 8, 10,  4,  3]])

In [ ]:
def im2col(input_data, filter_h, filter_w, stride=1,pad=0):
    """다수의 이미지를 입력받아 2차원 배열로 변환한다(평탄화)
    Parameters 
    ---------- 
    input_data : 4차원 배열 형태의 입력 데이터(이미지 수, 채널 수, 높이, 너비) 
    filter_h : 필터의 높이 
    filter_w : 필터의 너비 
    stride : 스트라이드 
    pad : 패딩 
    
    Returns 
    ------- 
    col : 2차원 배열     
    
    """
    
    N, C, H, W = input_data.shape
    out_h = (H + 2 * pad - filter_h) // stride + 1 # 위의 출력크기 공식을 이용하여 구현
    out_w = (w + 2 * pad - filter_w) // stride + 1 
    
    img = np.pad(input_data, [(0,0), (0,0), (pad,pad), (pad, pad)], 'constant')
    col = np.zeros((N, C, filter_h, filter_w, out_h, out_w))
    
    for y in range(filter_h):
        y_max = y + stride * out_h
        for x in range(filter_w):
            x_max = x + stride * out_w
            col[:, :, y, x, :, :] = img[:, :, y:y_max:stride, x:x_max:stride] 
            
    col = col.transpose(0, 4, 5, 1, 2, 3).reshape(N * out_h * out_w, -1)
    
    return col
    

In [44]:
a = [1,2,3,4,5,6,7,8,9]

In [60]:
a[1:8:1]

[2, 3, 4, 5, 6, 7, 8]

In [63]:
a[1:8:3]
# 3씩 건너뛴다

[2, 5, 8]